# Generated by Django 4.0.2 on 2022-02-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_rename_platform_watchlist_platforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platforms',
            new_name='platform',
        ),
    ]
